language: crystal
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq protobuf-compiler
- crystal build ./bin/protoc-gen-crystal.cr --release
- PATH=$PATH:$PWD protoc spec/fixtures/test.proto --crystal_out=./